### ISSUE TITLE
Some tif files failed to show layers info

### ISSUE THREAD

**Issue by yuriki** [cgohlke/psdtags#5]
Hi, 
With **some** (rare) tif files I have an issue with getting layers info:

```
Traceback (most recent call last):
  File "C:\Users\yuriy.l\AppData\Local\Autodesk\3dsMax\2021 - 64bit\ENU\scripts\fraglab_asset_checker_libs\psdtags\psdtags.py", line 263, in __call__
    c = enum.EnumMeta.__call__(cls, *args, **kwds)
  File "C:\Program Files\Autodesk\3ds Max 2021\Python37\lib\enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "C:\Program Files\Autodesk\3ds Max 2021\Python37\lib\enum.py", line 564, in __new__
    raise exc
  File "C:\Program Files\Autodesk\3ds Max 2021\Python37\lib\enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "C:\Program Files\Autodesk\3ds Max 2021\Python37\lib\enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: b'iOpa' is not a valid PsdKey

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yuriy.l\AppData\Local\Autodesk\3dsMax\2021 - 64bit\ENU\scripts\fraglab_asset_checker_libs\psdtags\psdtags.py", line 2967, in fromtiff
    data, name=os.path.split(filename)[-1], unknown=unknown
  File "C:\Users\yuriy.l\AppData\Local\Autodesk\3dsMax\2021 - 64bit\ENU\scripts\fraglab_asset_checker_libs\psdtags\psdtags.py", line 2951, in frombytes
    self = cls.read(fh, name=name, unknown=unknown)
  File "C:\Users\yuriy.l\AppData\Local\Autodesk\3dsMax\2021 - 64bit\ENU\scripts\fraglab_asset_checker_libs\psdtags\psdtags.py", line 2912, in read
    fh, psdformat, key, length=size, unknown=unknown
  File "C:\Users\yuriy.l\AppData\Local\Autodesk\3dsMax\2021 - 64bit\ENU\scripts\fraglab_asset_checker_libs\psdtags\psdtags.py", line 945, in read
    layers.append(PsdLayer.read(fh, psdformat, unknown=unknown))
  File "C:\Users\yuriy.l\AppData\Local\Autodesk\3dsMax\2021 - 64bit\ENU\scripts\fraglab_asset_checker_libs\psdtags\psdtags.py", line 1122, in read
    fh, psdformat, length=end - fh.tell(), unknown=unknown, align=2
  File "C:\Users\yuriy.l\AppData\Local\Autodesk\3dsMax\2021 - 64bit\ENU\scripts\fraglab_asset_checker_libs\psdtags\psdtags.py", line 3333, in read_psdtags
    key = PsdKey(fh.read(4))
  File "C:\Users\yuriy.l\AppData\Local\Autodesk\3dsMax\2021 - 64bit\ENU\scripts\fraglab_asset_checker_libs\psdtags\psdtags.py", line 265, in __call__
    raise exc
  File "C:\Users\yuriy.l\AppData\Local\Autodesk\3dsMax\2021 - 64bit\ENU\scripts\fraglab_asset_checker_libs\psdtags\psdtags.py", line 257, in __call__
    c = enum.EnumMeta.__call__(cls, *args, **kwds)
  File "C:\Program Files\Autodesk\3ds Max 2021\Python37\lib\enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "C:\Program Files\Autodesk\3ds Max 2021\Python37\lib\enum.py", line 564, in __new__
    raise exc
  File "C:\Program Files\Autodesk\3ds Max 2021\Python37\lib\enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "C:\Program Files\Autodesk\3ds Max 2021\Python37\lib\enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: b'apOi' is not a valid PsdKey
```

Please check the attached tif file:
[power_stone_core_d_ddna.zip](https://github.com/cgohlke/psdtags/files/10758584/power_stone_core_d_ddna.zip)

I'm executing Python 3.7.6 from MaxScript inside 3ds Max 2021
The next line raises the exception:
`imageSourceData = psdTagsLibrary.TiffImageSourceData.fromtiff(texturePath)`

psdtags ver. 2022.8.25

**Comment by cgohlke** [comment]
The file was created with Photoshop 2022. Adobe seems to have extended the PSD format but has not updated the [public documentation](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/). 

As a workaround, try to add `APOI = b'apOi'` to the `PsdKey` class in psdtags.py.

**Comment by yuriki** [comment]
Thank you. I did that but just FYI there is more than one new `PsdKey` 
I had also:
`ValueError: b' IAC' is not a valid PsdKey`

**Comment by cgohlke** [comment]
Can you also please share the file with the b' IAC' key?

Hopefully Adobe will document the new keys soon. If not, a way to handle unknown keys and structures needs to be added...

**Comment by cgohlke** [comment]
Should be fixed in version 2023.2.18, which allows unknown PsdKeys. A warning is logged.

**Comment by wdwhiteh** [comment]
> Should be fixed in version 2023.2.18, which allows unknown PsdKeys. A warning is logged.

I tried running with 2023.2.18, but still receive an exception for the b' IAC' key. In line 292, the "args[0].isalnum()" returns false because that key has a space in it. Therefore, the exception is still raised.

**Comment by cgohlke** [comment]
Are you sure b' IAC'  is a valid key? There is no precedence of any key starting with whitespace.

Please share a file and request documentation from Adobe support if you are a paying customer.

**Comment by wdwhiteh** [comment]
The file was generated from Photoshop version 24.0.0. I'll see if I can find the documentation.

**Comment by widdowson** [comment]
Can confirm I'm getting `psdtags.PsdKey(b'CAI ') not defined` with files from Photoshop 24.1.1. My files are LE32BIT.

**Comment by cgohlke** [comment]
Is that with the latest version, 2023.2.18.1?
